enable:
    issues: true
    prs: true

comments:
    issues: |
        Thanks for opening this issue! Applied any matching labels.
    prs: |
        Thanks for the PR! Applied any matching labels.

labels:
    'bug':
        include:
            - '\bFix\b'
    'enhancement':
        include:
            - '\bFeat\b'
    'documentation':
        include:
            - '\bDocs\b'
    'release':
        include:
            - '\bRelease\b'
    'refactoring':
        include:
            - '\bRefactor\b'
    'test':
        include:
            - '\bTest\b'