name: Auto labeler

# 트리거될 이벤트 설정
on:
    issues:
        types:
            - opened
            - edited
            - milestoned
    pull_request_target:
        types: [opened, synchronize, reopened]

# 트리거되었을 때 실행될 job 작성
jobs:
    labeler:
        # runner 설정
        runs-on: ubuntu-latest
        # 리파지토리에 대한 권한 설정
        permissions:
            contents: read
            issues: write
            pull-requests: write
        steps:
            - name: Check Labels
              id: labeler
              uses: jimschubert/labeler-action@v2
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}